### PR TITLE
Add node 4/5 to mirror

### PR DESCRIPTION
**Pull request by karenzshea**
https://github.com/mapbox/install-node/issues/32

- Added gpg keys for a few more members of the nodejs crew who've signed the 4/5 releases: rod vagg, jsenkpiel, jsnell
- windows builds are now uploaded to the dist page in additional `win-x64` and `win-x86` dirs. I've made our mirror reflect this change too and updated recache and `install-node` to account for it

post merge todo
- [ ] bump slugger
- [ ] bump buildpack

cc @springmeyer @yhahn @alulsh

### CODE REVIEW

**Comment by mikemorris** [comment]
Yay!

**Comment by springmeyer** [comment]
great stuff @karenzshea

**Comment by karenzshea** [comment]
@rclark @yhahn wanna :eyes: on this?

**Comment by yhahn** [comment]
@karenzshea :+1: awesome awesome work

**Pull request merged**
